<a href="https://colab.research.google.com/github/Jorge-Ruiz-Troccoli/Data-Science-II/blob/main/Clase%20005/Data_Wrangling_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo en Vivo parte 1

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
 'first': range(7)})
df1

  key  first
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'], 'second': range(3)})
df2

  key  second
0   a       0
1   b       1
2   d       2

In [ ]:
df3=pd.merge(left=df1,right=df2, on ='key',how='left')
df3

  key  first  second
0   b      0     1.0
1   b      1     1.0
2   a      2     0.0
3   c      3     NaN
4   a      4     0.0
5   a      5     0.0
6   b      6     1.0

Al tener un valor faltante una columna númerica por defecto pasa a ser float, reemplacemos por 999 como valor faltante y luego la convertimos en int.

In [ ]:
import numpy as np
df3["second"].replace(np.nan, 999, inplace=True)
df3["second"]=df3["second"].astype(int)
df3

  key  first  second
0   b      0       1
1   b      1       1
2   a      2       0
3   c      3     999
4   a      4       0
5   a      5       0
6   b      6       1

In [ ]:
#aplicamos un filtro para obtener un .describe()
#~ tilde de la Ñ o virgulilla

filtro=df3.second==999
df3.loc[~filtro]
#df3[~(df3.second==999)] otra forma de hacer lo mismo

  key  first  second
0   b      0       1
1   b      1       1
2   a      2       0
4   a      4       0
5   a      5       0
6   b      6       1

In [ ]:
# otra forma simple de hacer lo mismo
df3[df3.second!=999]
#df3[df3.second!=999].describe()

  key  first  second
0   b      0       1
1   b      1       1
2   a      2       0
4   a      4       0
5   a      5       0
6   b      6       1

In [ ]:
pd.merge(df1,df2, on ='key',how= 'inner')

  key  first  second
0   b      0       1
1   b      1       1
2   b      6       1
3   a      2       0
4   a      4       0
5   a      5       0

In [ ]:
pd.merge(df1,df2, on ='key',how= 'outer')

  key  first  second
0   b    0.0     1.0
1   b    1.0     1.0
2   b    6.0     1.0
3   a    2.0     0.0
4   a    4.0     0.0
5   a    5.0     0.0
6   c    3.0     NaN
7   d    NaN     2.0

In [ ]:
pd.merge(df1,df2, on ='key',how= 'right')

  key  first  second
0   a    2.0       0
1   a    4.0       0
2   a    5.0       0
3   b    0.0       1
4   b    1.0       1
5   b    6.0       1
6   d    NaN       2

In [ ]:
df2 = pd.DataFrame({'key': ['a', 'a', 'b', 'd'], 'second': [0,1,2,3]})
df2

  key  second
0   a       0
1   a       1
2   b       2
3   d       3

In [ ]:
pd.merge(df1,df2, on ='key',how= 'right')

  key  first  second
0   a    2.0       0
1   a    4.0       0
2   a    5.0       0
3   a    2.0       1
4   a    4.0       1
5   a    5.0       1
6   b    0.0       2
7   b    1.0       2
8   b    6.0       2
9   d    NaN       3

# Ejemplo en vivo Parte 2

In [ ]:
clase0=pd.read_excel('clase0.xlsx')
clase0

           key1  key2  data
0  Buenos Aires  2020     0
1  Buenos Aires  2021     1
2  Buenos Aires  2022     2
3       Cordoba  2021     3
4       Cordoba  2022     4
5      Santa Fe  2020     5
6      Santa Fe  2020     6

In [ ]:
clase1=pd.read_excel('clase1.xlsx')
clase1

           key1  key2  event1  event2
0       Cordoba  2021       0       1
1       Cordoba  2020       2       3
2  Buenos Aires  2020       4       5
3  Buenos Aires  2020       6       7
4  Buenos Aires  2021       8       9
5  Buenos Aires  2022      10      11
6      Santa Fe  2020      12      13
7      Santa Fe  2019      14      15

In [ ]:
clase1.groupby(by=['key1','key2']).mean()
# clase1.groupby(['key1','key2']).mean() se puede usar sin el by

                   event1  event2
key1         key2
Buenos Aires 2020     5.0     6.0
             2021     8.0     9.0
             2022    10.0    11.0
Cordoba      2020     2.0     3.0
             2021     0.0     1.0
Santa Fe     2019    14.0    15.0
             2020    12.0    13.0

In [ ]:

"""
La función pd.merge() en pandas se utiliza para combinar dos DataFrames en función de una
o más columnas comunes, especificadas mediante el parámetro on.
En este ejemplo, estamos realizando un merge entre los DataFrames clase0 y clase1 utilizando
las columnas 'key1' y 'key2' como claves de combinación.
"""
pd.merge(clase0, clase1, on =['key1','key2'])
# por defecto el "how"  es inner

           key1  key2  data  event1  event2
0  Buenos Aires  2020     0       4       5
1  Buenos Aires  2020     0       6       7
2  Buenos Aires  2021     1       8       9
3  Buenos Aires  2022     2      10      11
4       Cordoba  2021     3       0       1
5      Santa Fe  2020     5      12      13
6      Santa Fe  2020     6      12      13

In [ ]:
pd.merge(clase0,clase1, on =['key1','key2'],how= 'inner')

#igual al anterior pero siendo explícitos en el "how"

           key1  key2  data  event1  event2
0  Buenos Aires  2020     0       4       5
1  Buenos Aires  2020     0       6       7
2  Buenos Aires  2021     1       8       9
3  Buenos Aires  2022     2      10      11
4       Cordoba  2021     3       0       1
5      Santa Fe  2020     5      12      13
6      Santa Fe  2020     6      12      13

In [ ]:
"""
El parámetro how='outer' en la función pd.merge() indica que se realizará una combinación externa o
"outer join" entre los DataFrames que estás uniendo.
Esta opción de combinación incluye todas las filas de ambos DataFrames,
incluso aquellas que no tienen una coincidencia en las columnas de combinación especificadas.
"""

pd.merge(clase0,clase1, on =['key1','key2'],how= 'outer')

           key1  key2  data  event1  event2
0  Buenos Aires  2020   0.0     4.0     5.0
1  Buenos Aires  2020   0.0     6.0     7.0
2  Buenos Aires  2021   1.0     8.0     9.0
3  Buenos Aires  2022   2.0    10.0    11.0
4       Cordoba  2021   3.0     0.0     1.0
5       Cordoba  2022   4.0     NaN     NaN
6      Santa Fe  2020   5.0    12.0    13.0
7      Santa Fe  2020   6.0    12.0    13.0
8       Cordoba  2020   NaN     2.0     3.0
9      Santa Fe  2019   NaN    14.0    15.0

In [ ]:
"""
El parámetro how='left' en la función pd.merge() indica que se realizará una combinación izquierda o "left join"
entre los DataFrames que estás uniendo. En un left join, el resultado contendrá todas las filas del DataFrame de la izquierda
(el primer DataFrame en la función pd.merge()) y las filas coincidentes del DataFrame de la derecha (el segundo DataFrame en la función).

Si alguna fila del DataFrame de la izquierda no tiene una coincidencia en las columnas de combinación,
las columnas correspondientes del DataFrame de la derecha se llenarán con NaN (valores nulos).
"""



pd.merge(clase0,clase1, on =['key1','key2'],how= 'left')

           key1  key2  data  event1  event2
0  Buenos Aires  2020     0     4.0     5.0
1  Buenos Aires  2020     0     6.0     7.0
2  Buenos Aires  2021     1     8.0     9.0
3  Buenos Aires  2022     2    10.0    11.0
4       Cordoba  2021     3     0.0     1.0
5       Cordoba  2022     4     NaN     NaN
6      Santa Fe  2020     5    12.0    13.0
7      Santa Fe  2020     6    12.0    13.0

In [ ]:
"""
El parámetro how='right' en la función pd.merge() indica que se realizará una combinación derecha o "right join"
entre los DataFrames que estás uniendo. En un right join, el resultado contendrá todas las filas del DataFrame de la derecha
 y las filas coincidentes del DataFrame de la izquierda.

Si alguna fila del DataFrame de la derecha no tiene una coincidencia en las columnas de combinación,
las columnas correspondientes del DataFrame de la izquierda se llenarán con NaN (valores nulos).
"""


pd.merge(clase0,clase1, on =['key1','key2'],how= 'right')

           key1  key2  data  event1  event2
0       Cordoba  2021   3.0       0       1
1       Cordoba  2020   NaN       2       3
2  Buenos Aires  2020   0.0       4       5
3  Buenos Aires  2020   0.0       6       7
4  Buenos Aires  2021   1.0       8       9
5  Buenos Aires  2022   2.0      10      11
6      Santa Fe  2020   5.0      12      13
7      Santa Fe  2020   6.0      12      13
8      Santa Fe  2019   NaN      14      15

In [ ]:
# ahora veamos .concat()

"""pd.concat([c1, c2, c3, c4], axis=0) combina los DataFrames c1, c2, c3 y c4 uno debajo del otro,
creando un nuevo DataFrame que contiene todas las filas de los DataFrames originales de forma consecutiva.

El resultado tendrá la misma cantidad de columnas que los DataFrames originales y contendrá todas las filas de c1,
seguidas de todas las filas de c2, luego todas las filas de c3 y finalmente todas las filas de c4.

Es importante que los DataFrames deben tener las mismas columnas en el mismo orden para realizar una concatenación vertical adecuada."""


c1=pd.merge(clase0,clase1, on =['key1','key2'],how= 'right')
c2=pd.merge(clase0,clase1, on =['key1','key2'],how= 'left')
c3=pd.merge(clase0,clase1, on =['key1','key2'],how= 'outer')
c4=pd.merge(clase0,clase1, on =['key1','key2'],how= 'inner')
pd.concat([c1,c2,c3,c4],axis=0)

           key1  key2  data  event1  event2
0       Cordoba  2021   3.0     0.0     1.0
1       Cordoba  2020   NaN     2.0     3.0
2  Buenos Aires  2020   0.0     4.0     5.0
3  Buenos Aires  2020   0.0     6.0     7.0
4  Buenos Aires  2021   1.0     8.0     9.0
5  Buenos Aires  2022   2.0    10.0    11.0
6      Santa Fe  2020   5.0    12.0    13.0
7      Santa Fe  2020   6.0    12.0    13.0
8      Santa Fe  2019   NaN    14.0    15.0
0  Buenos Aires  2020   0.0     4.0     5.0
1  Buenos Aires  2020   0.0     6.0     7.0
2  Buenos Aires  2021   1.0     8.0     9.0
3  Buenos Aires  2022   2.0    10.0    11.0
4       Cordoba  2021   3.0     0.0     1.0
5       Cordoba  2022   4.0     NaN     NaN
6      Santa Fe  2020   5.0    12.0    13.0
7      Santa Fe  2020   6.0    12.0    13.0
0  Buenos Aires  2020   0.0     4.0     5.0
1  Buenos Aires  2020   0.0     6.0     7.0
2  Buenos Aires  2021   1.0     8.0     9.0
3  Buenos Aires  2022   2.0    10.0    11.0
4       Cordoba  2021   3.0     0.0     1.0
5       Cordoba  2022   4.0     NaN     NaN
6      Santa Fe  2020   5.0    12.0    13.0
7      Santa Fe  2020   6.0    12.0    13.0
8       Cordoba  2020   NaN     2.0     3.0
9      Santa Fe  2019   NaN    14.0    15.0
0  Buenos Aires  2020   0.0     4.0     5.0
1  Buenos Aires  2020   0.0     6.0     7.0
2  Buenos Aires  2021   1.0     8.0     9.0
3  Buenos Aires  2022   2.0    10.0    11.0
4       Cordoba  2021   3.0     0.0     1.0
5      Santa Fe  2020   5.0    12.0    13.0
6      Santa Fe  2020   6.0    12.0    13.0

In [ ]:
c1

           key1  key2  data  event1  event2
0       Cordoba  2021   3.0       0       1
1       Cordoba  2020   NaN       2       3
2  Buenos Aires  2020   0.0       4       5
3  Buenos Aires  2020   0.0       6       7
4  Buenos Aires  2021   1.0       8       9
5  Buenos Aires  2022   2.0      10      11
6      Santa Fe  2020   5.0      12      13
7      Santa Fe  2020   6.0      12      13
8      Santa Fe  2019   NaN      14      15

In [ ]:
#probemos que pasa si eliminamos la columna data del df c1
c1.drop("data", axis=1, inplace=True)
c1

           key1  key2  event1  event2
0       Cordoba  2021       0       1
1       Cordoba  2020       2       3
2  Buenos Aires  2020       4       5
3  Buenos Aires  2020       6       7
4  Buenos Aires  2021       8       9
5  Buenos Aires  2022      10      11
6      Santa Fe  2020      12      13
7      Santa Fe  2020      12      13
8      Santa Fe  2019      14      15

In [ ]:
pd.concat([c1,c2,c3,c4],axis=0)
#podemos ver que en data c1 va aparecer ahora valores NaN

           key1  key2  event1  event2  data
0       Cordoba  2021     0.0     1.0   NaN
1       Cordoba  2020     2.0     3.0   NaN
2  Buenos Aires  2020     4.0     5.0   NaN
3  Buenos Aires  2020     6.0     7.0   NaN
4  Buenos Aires  2021     8.0     9.0   NaN
5  Buenos Aires  2022    10.0    11.0   NaN
6      Santa Fe  2020    12.0    13.0   NaN
7      Santa Fe  2020    12.0    13.0   NaN
8      Santa Fe  2019    14.0    15.0   NaN
0  Buenos Aires  2020     4.0     5.0   0.0
1  Buenos Aires  2020     6.0     7.0   0.0
2  Buenos Aires  2021     8.0     9.0   1.0
3  Buenos Aires  2022    10.0    11.0   2.0
4       Cordoba  2021     0.0     1.0   3.0
5       Cordoba  2022     NaN     NaN   4.0
6      Santa Fe  2020    12.0    13.0   5.0
7      Santa Fe  2020    12.0    13.0   6.0
0  Buenos Aires  2020     4.0     5.0   0.0
1  Buenos Aires  2020     6.0     7.0   0.0
2  Buenos Aires  2021     8.0     9.0   1.0
3  Buenos Aires  2022    10.0    11.0   2.0
4       Cordoba  2021     0.0     1.0   3.0
5       Cordoba  2022     NaN     NaN   4.0
6      Santa Fe  2020    12.0    13.0   5.0
7      Santa Fe  2020    12.0    13.0   6.0
8       Cordoba  2020     2.0     3.0   NaN
9      Santa Fe  2019    14.0    15.0   NaN
0  Buenos Aires  2020     4.0     5.0   0.0
1  Buenos Aires  2020     6.0     7.0   0.0
2  Buenos Aires  2021     8.0     9.0   1.0
3  Buenos Aires  2022    10.0    11.0   2.0
4       Cordoba  2021     0.0     1.0   3.0
5      Santa Fe  2020    12.0    13.0   5.0
6      Santa Fe  2020    12.0    13.0   6.0

In [ ]:
"""
el parámetro axis=1 en pandas se utiliza para indicar que se aplicará el método
a lo largo del eje horizontal (columnas) en lugar del eje vertical (filas).
"""

a=pd.concat([c1,c2],axis=1)
#a=pd.concat([c1,c2],axis="columns")
a

,key1,key2,event1,event2,key1,key2,data,event1,event2
0,Cordoba,2021,0,1,Buenos Aires,2020.0,0.0,4.0,5.0
1,Cordoba,2020,2,3,Buenos Aires,2020.0,0.0,6.0,7.0
2,Buenos Aires,2020,4,5,Buenos Aires,2021.0,1.0,8.0,9.0
3,Buenos Aires,2020,6,7,Buenos Aires,2022.0,2.0,10.0,11.0
4,Buenos Aires,2021,8,9,Cordoba,2021.0,3.0,0.0,1.0
5,Buenos Aires,2022,10,11,Cordoba,2022.0,4.0,NaN,NaN
6,Santa Fe,2020,12,13,Santa Fe,2020.0,5.0,12.0,13.0
7,Santa Fe,2020,12,13,Santa Fe,2020.0,6.0,12.0,13.0
8,Santa Fe,2019,14,15,NaN,NaN,NaN,NaN,NaN

# Cuidado al usar concat!!!

In [ ]:
# Crear el primer DataFrame
ID1= [1, 2, 3]
data1 = {'Nombre': ['Juan', 'María', 'Pedro']}
df1 = pd.DataFrame(data1, index=ID1)


ID2= [4, 5,3]
# Crear el segundo DataFrame
data2 = {'Apellido': ['Herrera', 'Lopez', 'Osorio']}
df2 = pd.DataFrame(data2, index=ID2)

In [ ]:
df1

  Nombre
1   Juan
2  María
3  Pedro

In [ ]:
df2

  Apellido
4  Herrera
5    Lopez
3   Osorio

In [ ]:
# Concatenar los DataFrames
df_concat = pd.concat([df1, df2], axis=1)

# Imprimir el DataFrame concatenado
df_concat

  Nombre Apellido
1   Juan      NaN
2  María      NaN
3  Pedro   Osorio
4    NaN  Herrera
5    NaN    Lopez

Podemos igualar los index como opción.

In [ ]:
df2.index=df1.index
df2

  Apellido
1  Herrera
2    Lopez
3   Osorio

In [ ]:
# Concatenar los DataFrames
df_concat = pd.concat([df1, df2], axis=1)

# Imprimir el DataFrame concatenado
df_concat

  Nombre Apellido
1   Juan  Herrera
2  María    Lopez
3  Pedro   Osorio